name = "blockchain-digital-notary"

[service]
image = "getlevvel/blockchain-digital-notary"
ports = [ "11113:11113" ]
volumes = [  ]
environment = [  ]

[services]
#validators will have chain as dep
#light clients shouldn't have to run a tmint node
dependencies = [ "ipfs", "eris/keys" ] 

[maintainer]
name = "Levvel"
email = "hello@levvel.io"

[location]
repository = "github.com/getlevvel/blockchain-digital-notary"

[machine]
include = [ "docker" ]
requires = [ "" ]
